public class AddAccountController {
    
    public List <Account> account=new List <Account>();
    public Account act{get;set;}
    
    public AddAccountController() {       
        act = new Account();
    }
    
    public List <Account> getAccount() {
        account = [SELECT Id, Name, Site, Type FROM Account order by createddate desc limit 20];
        return account;
    }
    
    public PageReference cancel() {
        return null;
    }
    
    public PageReference save() {
        system.debug('act name:' + act.name + ' = ' + act.accountNumber);
        if(act.accountNumber=='1')
        {
            act.accountNumber.addError('Please enter proper act no');
            return null;
        }
        
        upsert act;
        return null;
    }
}